### ISSUE TITLE
Plans to update for 2.1?

### ISSUE THREAD

**Issue by sethgregory** [d3dev/d3_tooltips#5]
Unfortunately, this no longer seems to work with the current version.  Any plans to update?  Thanks!

**Comment by d3dev** [comment]
Hi @sethgregory thank you for letting me know.
 
Some new fields added to the "tooltip" structure have moved the offsets of HexSpeak-magic-numbers few bytes back. You might have figured it out by taking a look to the memory layout as depicted in the wiki.

Sorry for the way too late reply.
